<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="tiles" tilewidth="8" tileheight="8" tilecount="400" columns="20">
 <image source="tiles.png" width="160" height="160"/>
 <tile id="0" type="grass"/>
 <tile id="1" type="grass_1"/>
 <tile id="2" type="grass_2"/>
 <tile id="3" type="grass_3"/>
 <tile id="4" type="grass_water_south_west"/>
 <tile id="5" type="grass_water_south"/>
 <tile id="6" type="grass_water_south_east"/>
 <tile id="7" type="grass_water_west"/>
 <tile id="8" type="grass_water_east"/>
 <tile id="9" type="grass_water_north_west"/>
 <tile id="10" type="grass_water_north"/>
 <tile id="11" type="grass_water_north_east"/>
 <tile id="12" type="grass_water_north_and_east"/>
 <tile id="13" type="grass_water_north_and_west"/>
 <tile id="14" type="grass_water_south_and_east"/>
 <tile id="15" type="grass_water_south_and_west"/>
 <tile id="20" type="water_shallow"/>
 <tile id="21" type="water_shallow_wave"/>
 <tile id="22" type="water_shallow_wave_alt"/>
 <tile id="23" type="water_shallow_turbulent"/>
 <tile id="24" type="water_shallow_lilly"/>
 <tile id="25" type="water_shallow_dirt"/>
 <tile id="26" type="beach_top_left"/>
 <tile id="27" type="beach_top"/>
 <tile id="28" type="beach_top_right"/>
 <tile id="29" type="beach_bottom_left"/>
 <tile id="30" type="beach_bottom"/>
 <tile id="31" type="beach_bottom_right"/>
 <tile id="32" type="beach_left"/>
 <tile id="33" type="beach_right"/>
 <tile id="38" type="beach"/>
 <tile id="40" type="water_deep"/>
 <tile id="41" type="water_deep_wave"/>
 <tile id="42" type="water_deep_wave_alt"/>
 <tile id="43" type="water_deep_turbulent"/>
 <tile id="380" type="void"/>
 <tile id="381" type="void_grass"/>
 <tile id="382" type="void_brick"/>
 <tile id="383" type="void_water"/>
</tileset>
